### PR TITLE
Prepped

### PR DESCRIPTION
**Pull request by ThomasTJdev**

### CODE REVIEW

**Comment by ThomasTJdev** [comment]
@mantielero - Do you have any progress on nimterop? This also a solution.

**Comment by mantielero** [comment]
I have stalled that. I am not a pro-dev so I struggle with the wrappers when I hit a wall. :o(

**Comment by ThomasTJdev** [comment]
Are you using Linux? Could you then try this PR? Thank you.

**Comment by mantielero** [comment]
I run `nimble test`in my ArchLinux and everything worked fine.

**Pull request merged**
